/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LessonsRouteRouteImport } from './routes/lessons/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonsIntroRouteImport } from './routes/lessons/intro'
import { Route as LessonsSketchTypeIdRouteImport } from './routes/lessons/$sketch.$type.$id'

const LessonsRouteRoute = LessonsRouteRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIntroRoute = LessonsIntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => LessonsRouteRoute,
} as any)
const LessonsSketchTypeIdRoute = LessonsSketchTypeIdRouteImport.update({
  id: '/$sketch/$type/$id',
  path: '/$sketch/$type/$id',
  getParentRoute: () => LessonsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lessons': typeof LessonsRouteRouteWithChildren
  '/lessons/intro': typeof LessonsIntroRoute
  '/lessons/$sketch/$type/$id': typeof LessonsSketchTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lessons': typeof LessonsRouteRouteWithChildren
  '/lessons/intro': typeof LessonsIntroRoute
  '/lessons/$sketch/$type/$id': typeof LessonsSketchTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lessons': typeof LessonsRouteRouteWithChildren
  '/lessons/intro': typeof LessonsIntroRoute
  '/lessons/$sketch/$type/$id': typeof LessonsSketchTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lessons' | '/lessons/intro' | '/lessons/$sketch/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lessons' | '/lessons/intro' | '/lessons/$sketch/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/lessons'
    | '/lessons/intro'
    | '/lessons/$sketch/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LessonsRouteRoute: typeof LessonsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/intro': {
      id: '/lessons/intro'
      path: '/intro'
      fullPath: '/lessons/intro'
      preLoaderRoute: typeof LessonsIntroRouteImport
      parentRoute: typeof LessonsRouteRoute
    }
    '/lessons/$sketch/$type/$id': {
      id: '/lessons/$sketch/$type/$id'
      path: '/$sketch/$type/$id'
      fullPath: '/lessons/$sketch/$type/$id'
      preLoaderRoute: typeof LessonsSketchTypeIdRouteImport
      parentRoute: typeof LessonsRouteRoute
    }
  }
}

interface LessonsRouteRouteChildren {
  LessonsIntroRoute: typeof LessonsIntroRoute
  LessonsSketchTypeIdRoute: typeof LessonsSketchTypeIdRoute
}

const LessonsRouteRouteChildren: LessonsRouteRouteChildren = {
  LessonsIntroRoute: LessonsIntroRoute,
  LessonsSketchTypeIdRoute: LessonsSketchTypeIdRoute,
}

const LessonsRouteRouteWithChildren = LessonsRouteRoute._addFileChildren(
  LessonsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LessonsRouteRoute: LessonsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
